# Generated by Django 4.0.4 on 2022-07-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', 'bak_0006_manual_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telescopeprojectid',
            name='password',
            field=models.CharField(help_text='The project password for the telescope used to automatically schedule observations.', max_length=64, verbose_name='Telescope Project Password'),
        ),
    ]
