# Generated by Django 4.0.4 on 2022-07-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0001_squashed_0002_alter_telescopeprojectid_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observations',
            name='obsid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
