# Generated by Django 4.0.4 on 2022-07-14 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0002_proposalsettings_atca_min_exptime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telescopeprojectid',
            name='atca_email',
        ),
    ]
