# Generated by Django 4.0.4 on 2022-07-22 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0002_rename_adminalerts_alertpermission'),
        ('trigger_app', '0003_alter_observations_obsid'),
    ]

    operations = [
    ]
