# Generated by Django 4.0.4 on 2022-07-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0003_remove_telescopeprojectid_atca_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='telescopeprojectid',
            name='atca_email',
            field=models.CharField(blank=True, help_text='The email address of someone that was on the ATCA observing proposal. This is an authentication step only required for ATCA.', max_length=256, null=True, verbose_name='ATCA Proposal Email'),
        ),
    ]
