# Generated by Django 4.0.4 on 2022-07-25 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('trigger_app', '0005_rename_triggerid_eventgroup_and_more'), ('trigger_app', '0006_rename_trigger_group_id_proposaldecision_event_group_id_and_more'), ('trigger_app', '0007_rename_trigger_id_eventgroup_trig_id'), ('trigger_app', '0008_rename_voevent_event'), ('trigger_app', '0009_rename_trig_any_duration_proposalsettings_event_any_duration_and_more')]

    dependencies = [
        ('trigger_app', '0004_merge_20220722_0516'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TriggerID',
            new_name='EventGroup',
        ),
        migrations.RenameField(
            model_name='proposaldecision',
            old_name='trigger_id',
            new_name='trig_id',
        ),
        migrations.RenameField(
            model_name='voevent',
            old_name='trigger_id',
            new_name='trig_id',
        ),
        migrations.AlterField(
            model_name='proposalsettings',
            name='atca_band_15mm_exptime',
            field=models.IntegerField(default=60, help_text='Total exposure time of the observation cycle at this frequency band.', verbose_name='Band Exposure Time (mins)'),
        ),
        migrations.AlterField(
            model_name='proposalsettings',
            name='atca_band_16cm_exptime',
            field=models.IntegerField(default=60, help_text='Total exposure time of the observation cycle at this frequency band.', verbose_name='Band Exposure Time (mins)'),
        ),
        migrations.AlterField(
            model_name='proposalsettings',
            name='atca_band_3mm_exptime',
            field=models.IntegerField(default=60, help_text='Total exposure time of the observation cycle at this frequency band.', verbose_name='Band Exposure Time (mins)'),
        ),
        migrations.AlterField(
            model_name='proposalsettings',
            name='atca_band_4cm_exptime',
            field=models.IntegerField(default=60, help_text='Total exposure time of the observation cycle at this frequency band.', verbose_name='Band Exposure Time (mins)'),
        ),
        migrations.AlterField(
            model_name='proposalsettings',
            name='atca_band_7mm_exptime',
            field=models.IntegerField(default=60, help_text='Total exposure time of the observation cycle at this frequency band.', verbose_name='Band Exposure Time (mins)'),
        ),
        migrations.RenameField(
            model_name='proposaldecision',
            old_name='trigger_group_id',
            new_name='event_group_id',
        ),
        migrations.RenameField(
            model_name='voevent',
            old_name='trigger_group_id',
            new_name='event_group_id',
        ),
        migrations.RenameField(
            model_name='eventgroup',
            old_name='trigger_id',
            new_name='trig_id',
        ),
        migrations.RenameModel(
            old_name='VOEvent',
            new_name='Event',
        ),
        migrations.RenameField(
            model_name='proposalsettings',
            old_name='trig_any_duration',
            new_name='event_any_duration',
        ),
        migrations.RenameField(
            model_name='proposalsettings',
            old_name='trig_max_duration',
            new_name='event_max_duration',
        ),
        migrations.RenameField(
            model_name='proposalsettings',
            old_name='trig_min_duration',
            new_name='event_min_duration',
        ),
        migrations.AlterField(
            model_name='eventtelescope',
            name='name',
            field=models.CharField(help_text='Telescope that we receive Events from (e.g. SWIFT or Fermi)', max_length=64, unique=True, verbose_name='Event Telescope name'),
        ),
        migrations.AlterField(
            model_name='proposalsettings',
            name='event_telescope',
            field=models.ForeignKey(blank=True, help_text='The telescope that this proposal will accept at least one Event from before observing. Leave blank if you want to accept all telescopes.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='trigger_app.eventtelescope', to_field='name'),
        ),
        migrations.AlterField(
            model_name='proposalsettings',
            name='maximum_position_uncertainty',
            field=models.FloatField(default=0.05, help_text='A Event must have less than or equal to this position uncertainty to be observed.', verbose_name='Maximum Position Uncertainty (deg)'),
        ),
    ]
