# Generated by Django 4.0.4 on 2022-07-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0004_telescopeprojectid_atca_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalsettings',
            name='trig_any_duration',
            field=models.BooleanField(default=False, help_text='Will trigger on events with any duration which includes if they have None.', verbose_name='Any duration?'),
        ),
        migrations.AlterField(
            model_name='proposaldecision',
            name='decision',
            field=models.CharField(choices=[('P', 'Pending'), ('I', 'Ignored'), ('E', 'Error'), ('T', 'Triggered'), ('C', 'Canceled')], default='P', max_length=32),
        ),
    ]
