# Generated by Django 4.0.4 on 2022-07-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0005_rename_triggerid_eventgroup_and_more_squashed_0009_rename_trig_any_duration_proposalsettings_event_any_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgroup',
            name='ignored',
            field=models.BooleanField(default=True),
        ),
    ]
