# Generated by Django 4.0.4 on 2022-08-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0006_eventgroup_ignored'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='self_generated_trig_id',
            field=models.BooleanField(default=True),
        ),
    ]
