# Generated by Django 4.0.4 on 2022-07-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0006_rename_trigger_group_id_proposaldecision_event_group_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventgroup',
            old_name='trigger_id',
            new_name='trig_id',
        ),
    ]
