# Generated by Django 4.0.4 on 2023-01-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0007_event_self_generated_trig_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='trig_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='trig_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='proposaldecision',
            name='trig_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
