# Generated by Django 4.0.4 on 2022-07-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0007_rename_trigger_id_eventgroup_trig_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VOEvent',
            new_name='Event',
        ),
    ]
