# Generated by Django 4.0.4 on 2022-07-25 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0008_rename_voevent_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposalsettings',
            old_name='trig_any_duration',
            new_name='event_any_duration',
        ),
        migrations.RenameField(
            model_name='proposalsettings',
            old_name='trig_max_duration',
            new_name='event_max_duration',
        ),
        migrations.RenameField(
            model_name='proposalsettings',
            old_name='trig_min_duration',
            new_name='event_min_duration',
        ),
        migrations.AlterField(
            model_name='eventtelescope',
            name='name',
            field=models.CharField(help_text='Telescope that we receive Events from (e.g. SWIFT or Fermi)', max_length=64, unique=True, verbose_name='Event Telescope name'),
        ),
        migrations.AlterField(
            model_name='proposalsettings',
            name='event_telescope',
            field=models.ForeignKey(blank=True, help_text='The telescope that this proposal will accept at least one Event from before observing. Leave blank if you want to accept all telescopes.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='trigger_app.eventtelescope', to_field='name'),
        ),
        migrations.AlterField(
            model_name='proposalsettings',
            name='maximum_position_uncertainty',
            field=models.FloatField(default=0.05, help_text='A Event must have less than or equal to this position uncertainty to be observed.', verbose_name='Maximum Position Uncertainty (deg)'),
        ),
    ]
