# Generated by Django 4.0.4 on 2023-01-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0008_alter_event_trig_id_alter_eventgroup_trig_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgroup',
            name='event_observed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='possibleeventassociation',
            name='event_observed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
