# Generated by Django 4.0.4 on 2023-01-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0008_event_lvc_binary_black_hole_probability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lvc_event_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='lvc_significance',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='proposalsettings',
            name='minimum_binary_neutron_star_probability',
            field=models.FloatField(default=0.01, verbose_name='Minimum probability for event to be BNS'),
        ),
        migrations.AlterField(
            model_name='proposalsettings',
            name='minimum_neutron_star_black_hole_probability',
            field=models.FloatField(default=0.01, verbose_name='Minimum probability for event to be NSBH'),
        ),
        migrations.AlterField(
            model_name='proposalsettings',
            name='minimum_neutron_star_probability',
            field=models.FloatField(default=0.01, help_text='PROB_NS - probability that at least one object in the binary has a mass that is less than 3 solar masses', verbose_name='Minimum on the probability that at least one object in the binary has a mass that is less than 3 solar masses'),
        ),
    ]
