# Generated by Django 4.0.4 on 2023-01-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0009_eventgroup_event_observed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lvc_classification_BBH',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='lvc_classification_BNS',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='lvc_classification_NSBH',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='lvc_classification_Terrestrial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='lvc_prob_density_tile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='lvc_retraction_message',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='lvc_skymap_fits',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
