# Generated by Django 4.0.4 on 2023-02-06 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0009_alter_event_lvc_skymap_file'),
        ('trigger_app', '0009_event_hess_significance_and_more'),
    ]

    operations = [
    ]
