# Generated by Django 4.0.4 on 2023-01-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0009_event_lvc_event_url_event_lvc_significance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalsettings',
            name='observe_low_significance',
            field=models.BooleanField(default=True, help_text='2/day > FAR > (1/month CBC and 1/year BURST)', verbose_name='Observe events with low significance (high FAR)'),
        ),
        migrations.AddField(
            model_name='proposalsettings',
            name='observe_significant',
            field=models.BooleanField(default=True, help_text='(1/month CBC and 1/year BURST) > FAR', verbose_name='Observe events with high significance (low FAR)'),
        ),
    ]
