# Generated by Django 4.0.4 on 2023-02-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0010_merge_20230206_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalsettings',
            name='priority',
            field=models.IntegerField(default=1, help_text='Set proposal processing priority (lower is better)'),
        ),
    ]
