# Generated by Django 4.0.4 on 2023-01-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0010_event_lvc_classification_bbh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalsettings',
            name='cancel_observation_on_retraction',
            field=models.BooleanField(default=True, help_text='Cancel observations for this event if retraction notice sent by LVC'),
        ),
        migrations.AddField(
            model_name='proposalsettings',
            name='maximum_terrestial_probability',
            field=models.FloatField(default=0.95, help_text='Limit on the probability that the source is terrestrial (i.e., a background noise fluctuation or a glitch)', verbose_name='Maximum probability for event to be terrestial'),
        ),
        migrations.AddField(
            model_name='proposalsettings',
            name='minimum_mass_gap_probability',
            field=models.FloatField(default=0.01, help_text='Limit on the probability that at least one object in the binary has a mass between 3 and 5 solar masses', verbose_name='Minimum mass gap probability for observation'),
        ),
        migrations.AddField(
            model_name='proposalsettings',
            name='minimum_neutron_star_probability',
            field=models.FloatField(default=0.01, help_text='Limit on the probability that at least one object in the binary has a mass that is less than 3 solar masses', verbose_name='Minimum neutron star probability for observation'),
        ),
        migrations.AddField(
            model_name='proposalsettings',
            name='start_observation_at_high_sensitivity',
            field=models.BooleanField(default=True, help_text='On early warnings there will not be positional data so aim MWA in sub array mode at the high sensitivity area over the indian ocean'),
        ),
        migrations.AddField(
            model_name='proposalsettings',
            name='update_observation_using_skymap',
            field=models.BooleanField(default=True, help_text='On initial and update alerts there will be positional data so aim MWA in full array mode at the best position for observation, or cancel if bad position for MWA'),
        ),
    ]
