# Generated by Django 4.0.4 on 2023-01-20 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0011_proposalsettings_cancel_observation_on_retraction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='lvc_classification_BBH',
            new_name='mass_gap_probability',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='lvc_classification_BNS',
            new_name='neutron_star_probability',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='lvc_classification_NSBH',
            new_name='terrestial_probability',
        ),
        migrations.RemoveField(
            model_name='event',
            name='lvc_classification_Terrestrial',
        ),
    ]
