# Generated by Django 4.0.4 on 2023-03-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0012_cometlog_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='associated_event_id',
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='source_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='PossibleEventAssociation',
        ),
    ]
