# Generated by Django 4.0.4 on 2023-01-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0012_rename_lvc_classification_bbh_event_mass_gap_probability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalsettings',
            name='source_type',
            field=models.CharField(choices=[('GRB', 'Gamma-ray burst'), ('FS', 'Flare star'), ('NU', 'Neutrino'), ('GW', 'Gravitational wave')], max_length=3, verbose_name='What type of source will you trigger on?'),
        ),
        migrations.AlterField(
            model_name='proposalsettings',
            name='start_observation_at_high_sensitivity',
            field=models.BooleanField(default=True, help_text='On early warnings there will not be positional data so start MWA in sub array mode at the high sensitivity area over the indian ocean', verbose_name='Start observations at high sensitivity area using MWA sub array on early alerts'),
        ),
        migrations.AlterField(
            model_name='proposalsettings',
            name='update_observation_using_skymap',
            field=models.BooleanField(default=True, help_text='On initial and update alerts there will be positional data so start MWA in full array mode at the best position for observation, or cancel if bad position for MWA', verbose_name='Update observations with MWA full or sub array on alerts containing positional data'),
        ),
    ]
