# Generated by Django 4.0.4 on 2023-01-23 05:22

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0013_alter_proposalsettings_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lvc_skymap_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/skymaps'), upload_to=''),
        ),
    ]
