# Generated by Django 4.0.4 on 2023-03-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0013_remove_event_associated_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalsettings',
            name='atca_dec_max_1',
            field=models.IntegerField(default=-10, help_text='Only observe within this range', verbose_name='Declination max limit 1 (deg)'),
        ),
        migrations.AddField(
            model_name='proposalsettings',
            name='atca_dec_max_2',
            field=models.IntegerField(default=90, help_text='Only observe within this range', verbose_name='Declination max limit 2 (deg)'),
        ),
        migrations.AddField(
            model_name='proposalsettings',
            name='atca_dec_min_1',
            field=models.IntegerField(default=-90, help_text='Only observe within this range', verbose_name='Declination min limit 1 (deg)'),
        ),
        migrations.AddField(
            model_name='proposalsettings',
            name='atca_dec_min_2',
            field=models.IntegerField(default=-90, help_text='Only observe within this range', verbose_name='Declination min limit 2 (deg)'),
        ),
    ]
