# Generated by Django 4.0.4 on 2023-01-23 08:20

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0015_proposaldecision_alt_proposaldecision_az'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lvc_skymap_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/dylan/development/TraceT/webapp_tracet/media//skymaps'), upload_to=''),
        ),
    ]
