# Generated by Django 4.0.4 on 2022-07-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0005_proposalsettings_trig_any_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telescopeprojectid',
            name='password',
            field=models.CharField(max_length=1024, verbose_name="Telescope Project Password", help_text="The project password for the telescope used to automatically schedule observations."),
        ),
    ]

